Rails.application.routes.draw do
  
  get 'chats/top'
  get "/chats/:id/:book_id/:chapter_id/writing_book" => "chats#writing_book"
  get "/chats/:id/:book_id/:chapter_id/add_chracter" => "chats#add_chracter"
  post "/chats/:id/:book_id/:chapter_id/book_open" => "chats#book_open"
  post "/chats/:id/:book_id/:chapter_id/book_unopen" => "chats#book_unopen"
  post "/chats/:id/:book_id/:chapter_id/change_title" => "chats#change_title"
  post "/chats/:id/:book_id/:chapter_id/add_character_post" => "chats#add_character_post"
  post "/chats/:id/:book_id/:chapter_id/:character_id/edit_character_post" => "chats#edit_character_post"
  post "/chats/:id/:book_id/:chat_id/creat_script" => "chats#creat_script"
  post "/chats/:id/:book_id/:chapter_id/:script_id/edit_script" => "chats#edit_script"
  post "/chats/:id/:book_id/:chapter_id/:script_id/delete_script" => "chats#delete_script"

  
  
  get "/reader_register" => "user#reader_register"
  get "/author_register" => "user#author_register"
  get "/users/ManagerAccount" => "user#ManagerAccount"
  get "/login_form" => "user#login_form"
  get "/forget_password" => "user#forget_password"
  get "/confirm_login" => "user#confirm_login"
  get "/users/:id/author_central" => "user#author_central"
  get "/users/:id/reader_central" => "user#reader_central"
  get "/users/:id/new_book_register" => "user#new_book_register"
  get "/users/:id/edit_user" => "user#edit_user"
  get "/users/:id/edit_reader" => "user#edit_reader"
  get "/users/:id/:book_id/:chat_id/edit_book_register" => "user#edit_book_register"
  get "/users/:id/:book_id/first_chapter" => "user#first_chapter"
  get "/users/:id/:book_id/:chapter_id/next_chapter" => "user#next_chapter"
  get "/users/:id/:bookId/book_table_author" => "user#book_table_author"
  get "/users/:id/:book_id/:chapter_id/:comment_id/comment_share" => "user#comment_share"
  post "/users/:id/:book_id/:chapter_id/confirm_chapter" => "user#confirm_chapter"
  post "/users/:id/:book_id/:chat_id/edit_book_register_post" => "user#edit_book_register_post"
  post "/users/create_writer" => "user#create_writer"
  post "/users/create_reader" => "user#create_reader"
  post "/users/:id/edit_writer" => "user#edit_writer"
  post "/users/:id/edit_reading" => "user#edit_reading"
  post "/users/:id/create_book" => "user#create_book"
  post "/users/:id/:book_id/first_chapter_register" => "user#first_chapter_register"
  post "/users/:id/:book_id/:chapter_id/next_chapter_register" => "user#next_chapter_register"
  post "/login_post" => "user#login_post"
  post "/login_forget" => "user#login_forget"
  post "/logout" => "user#logout"
  post "/users/:id/:book_id/:chapter_id/post_comment" => "user#post_comment"
  post "/users/:id/:book_id/:chapter_id/:comment_id/comment_destroy" => "user#comment_destroy"
  post "/users/:id/:book_id/:chapter_id/:comment_id/central_commentDestroy" => "user#central_commentDestroy"
  post "/users/:id/:book_id/likeReading_destroy" => "user#likeReading_destroy"
  post "/users/:id/:book_id/chat_allOpen" => "user#chat_allOpen"
  post "/users/:id/:book_id/chat_allUnopen" => "user#chat_allUnopen"
  post "/users/:id/:user_id/aozora" => "user#aozora"
  post "/users/:id/:user_id/unopen_user" => "user#unopen_user"
  post "/users/:id/:user_id/open_user" => "user#open_user"
  post "/users/:id/:user_id/MNG_userDelete" => "user#MNG_userDelete"
  
  

  get "/" => "home#top"
  get "/termOfUse" => "home#termOfUse"
  get "/company_information" => "home#company_information"
  get "/privacy_policy" => "home#privacy_policy"
  get "/author_menu" => "home#author_menu"
  get "/category_all" => "home#category_all"
  get "/aozora_books" => "home#aozora_books"
  get "/:book_id/book_brief" => "home#book_brief"
  get "/:id/author_introduce" => "home#author_introduce"
  get "/:cat_number/:cat_word/:cat_image/each_category" => "home#each_category"
  get "/:book_id/:chapter_id/read_chapter" => "home#read_chapter"
  get "/:book_id/:chapter_id/read_comment" => "home#read_comment"
  post "/home/:id/:book_id/:chapter_id/:comment_id/good_comment" => "home#good_comment"
  post "/home/:id/:book_id/:chapter_id/:comment_id/bad_comment" => "home#bad_comment"
  post "/home/:id/:book_id/:chapter_id/:comment_id/good_destroy" => "home#good_destroy"
  post "/home/:id/:book_id/:chapter_id/:comment_id/bad_destroy" => "home#bad_destroy"
  post "/home/:id/:book_id/book_review" => "home#book_review"
  post "/home/:id/:book_id/edit_review" => "home#edit_review"
  post "/question" => "home#question"
  
  get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
